#!/bin/bash

#
# Sets up the build environment for perfkit
#

targets=" \
   build-essential \
   git-core \
   gnome-common \
   gtk-doc-tools \
   libavahi-glib-dev \
   libavahi-gobject-dev \
   libavahi-client-dev \
   libavahi-common-dev \
   libglib2.0-dev \
   libglib2.0-0-dbg \
   libgtk2.0-dev \
   libgtk2.0-0-dbg \
   libgoocanvas-dev \
   libdbus-glib-1-dev \
   libreadline-dev \
   valgrind \
   "

# install required packages
sudo apt-get install $targets

# build perfkit
./autogen.sh --enable-silent-rules
make
