#!/bin/bash

#
# Sets up the build environment for perfkit
#

ubuntu_targets=" \
   build-essential \
   git-core \
   gnome-common \
   gtk-doc-tools \
   libavahi-glib-dev \
   libavahi-gobject-dev \
   libavahi-client-dev \
   libavahi-common-dev \
   libglib2.0-dev \
   libglib2.0-0-dbg \
   libgtk2.0-dev \
   libgtk2.0-0-dbg \
   libgoocanvas-dev \
   libdbus-glib-1-dev \
   libreadline-dev \
   valgrind \
   "

fedora_targets=" \
   autoconf \
   libtool \
   glib2-devel \
   dbus-glib-devel \
   gtk2-devel \
   goocanvas-devel \
   readline-devel \
   avahi-gobject-devel \
   valgrind \
   "
# install required packages if possible
if hash sudo 2>/dev/null; then
  if hash apt-get 2>/dev/null; then
    sudo apt-get install $ubuntu_targets
  elif hash yum 2>/dev/null; then
    sudo yum install $fedora_targets
  fi
fi

# build perfkit
./autogen.sh --enable-silent-rules
make
